# Generated by Django 3.0.5 on 2020-04-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, verbose_name='검색키워드')),
                ('site', models.CharField(max_length=100, verbose_name='사이트')),
                ('used_id', models.CharField(max_length=100, verbose_name='아이디')),
                ('product_name', models.CharField(max_length=100, verbose_name='제품명')),
                ('product_price', models.IntegerField(verbose_name='제품가격')),
                ('company', models.CharField(max_length=100, verbose_name='공급업체')),
                ('price', models.IntegerField(verbose_name='공급_일반가')),
                ('discount_price', models.IntegerField(verbose_name='공급_할인가')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
            ],
            options={
                'verbose_name': '업체가격정보',
                'verbose_name_plural': '업체가격정보게시판',
                'db_table': 'crawled_data',
            },
        ),
    ]
